//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JadeKhalid_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SfiHdiEntitiesConnection : DbContext
    {
        public SfiHdiEntitiesConnection()
            : base("name=SfiHdiEntitiesConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<HDI> HDIs { get; set; }
        public virtual DbSet<Indicator> Indicators { get; set; }
        public virtual DbSet<SFI> SFIs { get; set; }
    }
}
