//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JadeKhalid_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indicator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Indicator()
        {
            this.SFIs = new HashSet<SFI>();
        }
    
        public int indicatorsID { get; set; }
        public int sfiID { get; set; }
        public double sfiTotal { get; set; }
        public double sfiSec { get; set; }
        public double sfiFaction { get; set; }
        public double sfiGgriev { get; set; }
        public double sfiEcon { get; set; }
        public double sfiEcIneq { get; set; }
        public double sfihFlight { get; set; }
        public double sfisLegit { get; set; }
        public double sfiPub { get; set; }
        public double sfiRights { get; set; }
        public double sfiDem { get; set; }
        public double sfiRef { get; set; }
        public double sfiExtInt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SFI> SFIs { get; set; }
    }
}
